version: '3'
services:
  db:
    container_name: twygo-api-db
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twygo_api_development
    networks:
      - twygo
  web:
    container_name: twygo-api-web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && tail -f /dev/null"
    volumes:
      - ./:/var/www/
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - twygo
  redis:
    container_name: twygo-api-redis
    image: redis:latest
    volumes:
      - ./tmp/redis:/data
    ports:
      - "6379:6379"
    networks:
      - twygo

networks:
  twygo:
    driver: bridge