default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: root
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twygo_api_development

test:
  <<: *default
  database: twygo_api_test

production:
  <<: *default
  database: twygo_api_production
  username: twygo_api
  password: <%= ENV["TWYGO_API_DATABASE_PASSWORD"] %>
